# Gratis + Rossmann keyword listesi
# marketfiyati.org.tr'de sonuç vermeyen ürünler
keywords:
  - ağız gargarası
  - el sabunu
  - roll-on deodorant
  - fondöten
  - rimel
  - güneş kremi
  - güneş losyonu
  - saç bakım yağı
  - menstrüel kap
